version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/AfterInstall.sh
      timeout: 300
      runas: root
