version: 0.0
os: linux
files:
  - source: /my-pizza-order-online
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 300
      runas: root
