#https://github.com/aws-actions/amazon-ecr-login/tree/main
#https://medium.com/@anshita.bhasin/build-and-push-docker-image-to-aws-ecr-using-github-actions-506e9f77f7f8
#https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
name: Push To ECR
on: 
  push: 
    branches: [ "master" ]
  
jobs:
  push-to-ecr:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout the repo
          uses: actions/checkout@v4   
          
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
            
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2          

        - name: Build, tag, and push docker image to Amazon ECR
          id: build and push
          env:
            REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_SHA: ${{ github.sha }} #get full commit id 40 words
          run: |
            IMAGE_TAG=${IMAGE_SHA:0:7} #Extracting the first 7 characters
            echo "commit id to use as tag is: $IMAGE_TAG"
            docker build -t $REGISTRY/$REPOSITORY:latest .
            docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            docker push $REGISTRY/$REPOSITORY:latest
