name: AWS cred test Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for particular region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1  # Specify your AWS region
          role-to-assume: arn:aws:iam::975050106552:role/test-OTDC-github-workflow  # Specify your IAM Role ARN for OIDC
          role-session-name: TestAwsCred

      - name: Test AWS CLI
        run: |
          aws sts get-caller-identity
          aws s3 ls  # Example command to list S3 buckets as a test
      - name: Create script for deployment
        run: |
          cat <<EOL > connection.sh
          ip addr
          curl ifconfig.me
              if echo "quit" | telnet 54.146.55.79 22 /dev/null 2>&1 | grep "Connected"; then
                 echo "Connection successful to test server."
              else
                  echo "Connection failed to test server."
              fi
          EOL
          echo "check connection to target server for ssh"
          nc -z -v -w 3 54.146.55.79 22
      - name: Run bash script
        run: |              
              ls -lrth
              echo "getting the detail for runner"
              pwd  
              ls -a ~
              
              #bash connection.sh
          

